### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by wooorm** [Wulf/nodehun#33]
Hi all! Great that a maintainer has been found. That’s really awesome, @Wulf. And thanks @nathanjsweet for your work so far <3

I’m planning on using a proper spell checker in a pretty big project. I previously used nodehun but due to post-0.12 issues I had to switch. There aren’t any good alternatives around (mainly, they don’t support buffers instead of files), so I tried to write my own in plain JS (it’s at 75% done now). Hunspell is much better than what I could ever do though, so I’d prefer to use bindings.

What I’m wondering is, how’s the future of nodehun going to look. For example, will there be updates of [nathanjsweet/hunspell-distributed](https://github.com/nathanjsweet/hunspell-distributed) as well, and how about upcoming versions of Node?

This sounds a bit push-y, I’m trying not to be, sorry. I’m wondering what both of your thoughts on the future are. @nathanjsweet, will you still answer issues / questions / review? Will this move over to wulf’s account? Etc. @Wulf, what are your thoughts?

Lastly, I’d love to help as well. I don’t know C, but I’m good at docs, tests, publishing, and most other non-C things :)

Cheers, and again, thanks both!

**Comment by nathanjsweet** [comment]
Hey Titus,
So Wulf has updated the project to keep up with node. He is active in node development, so he will continue to keep up with it. He will be taking over the project (it will move to his account), and he said that the has plans for implementing some known testing frameworks to have better test coverare. If you have documentation stuff you would like to add, I think he would be more than open to it, and maybe he wants to add more documentation as well. I will be only answer Wulf's questions on nodehun going forward, so he will be handling anyone else's questions.

I will keep hunspell-distributed under my account, and I am more than happy to meet any requests around it that you might have, including synchronizing it with the main project or adding new features. However, if changes are made to hunspell-distributed they won't show up in nodehun automatically. It will take further work with Wulf to make sure tests are passing and interfaces aren't broken to make sure that the updates don't break nodehun.

Feel free to ask more questions if you have them.

**Comment by Wulf** [comment]
Hey @wooorm! 

Yeah as Nathan mentioned, the first step should be setting up tests so that our updates don't break anything. A setup with mocha/chai will do the trick.

Also, help is always greatly appreciated! I'll try to make issues -- feel free to do the same. They can act as tasks that can be attacked one by one.

As for my thoughts on the future: my goal is to make sure nodehun can function in any node environment. What did you want to see or change?

**Comment by wooorm** [comment]
Oh that’s really awesome, you both <3

> [...] I am more than happy to meet any requests around it that you might have, including synchronizing it with the main project or adding new features. [...]

@nathanjsweet One of the things I’m especially interested in, is support for personal dictionaries (those without affixes, see Hunspell(5)), are those already supported in `hunspell-distributed`? And other than that, yes, I’d appreciate syncing with upstream!

> Yeah as Nathan mentioned, the first step should be setting up tests so that our updates don't break anything. A setup with mocha/chai will do the trick.

@Wulf I’ve got lots of tests from the lib I wrote, but they’re in [tape](https://www.npmjs.com/package/tape) (which is really good). OK if I open a PR adding those? (they should be portable).

> As for my thoughts on the future: my goal is to make sure nodehun can function in any node environment. What did you want to see or change?

@Wulf As noted above, I’m interested in support for personal dictionaries (as that would make it possible, without much work, for people to start creating dictionaries for their own projects). Other than that, nodehun is already really good.

My suggestions for upping this project are:

* [ ] Add tests (I can do that);
* [ ] Add proper description of available methods (I can do that);
* [ ] Add CIs (AppVeyor for Windows, Travis for OSX and Linux);
* [ ] Match Hunspell(3) interface.

**Comment by nathanjsweet** [comment]
@wooorm 
Can you add two issues in hunspell-distributed? One for synchronizing with upstream and one for exposing personal dictionaries? It may very well be that they're exposed. I don't know I haven't  investigated.

**Comment by Wulf** [comment]
@wooorm, We think alike :)

What I told Nathan when it came to features I wanted to add, dictionary management was one of them. Let's start a discussion around that in another issue. 

Regarding matching the Hunspell(3) interface, do you mean [this one](http://linux.die.net/man/3/hunspell)? So you're suggesting instead of something like `spellSuggestions`, we have `suggest` in the exposed javascript API?

**Comment by wooorm** [comment]
@nathanjsweet done!

@Wulf 👍 Also: could you add me as a collaborator? Makes it easier to work together :)

**Comment by wooorm** [comment]
P.S. IMO this can be closed? Seems the future is bright :)
