### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by Wulf** [Wulf/nodehun#36]
@wooorm has some tests which could be portable, written with [tape](https://github.com/substack/tape).

Edit `package.json` and make sure the property `scripts.test` is set properly.

**Comment by Wulf** [comment]
We should setup coverage after setting up tests.

**Comment by wooorm** [comment]
Yeah I can do that, only thing is that you should enable travis-ci, and codecov (which I suggest for coverage)

**Comment by wooorm** [comment]
@Wulf If you add me as a collaborator, I’ll add a first test and the test setup and we can work on the architecture / tests from then on?

**Comment by Pelsin** [comment]
@wooorm @Wulf You guys are doing a great job with this!
I just started using this package yesterday for a hobby project :https://github.com/Pelsin/Speri-Shecku
Thought at about making a PR with simple mocha testa for the finished build, but saw that you have created an issue for this and that @wooorm is on it! 👍 

I will hang around and see if there is anything i can help you guys with!

**Comment by Wulf** [comment]
@Pelsin Sounds good :)

@wooorm Awesome, I'll do that -- please don't push to master though, I prefer we have a separate branch for every issue ([feature branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow)). After it's good to go, we'll merge it in to master. I'll create a branch for this issue called `feature/tests`.

**Comment by Wulf** [comment]
Awesome @wooorm!
