### ISSUE TITLE
Match Hunspell(3) interface

### ISSUE THREAD

**Issue by Wulf** [Wulf/nodehun#37]
**Implementation Progress**
Branch: ~`nan`~ `n-api`

Implement methods

- [x] add*
- [x] addSync
- [x] remove
- [x] removeSync
- [x] suggest
- [x] suggestSync
- [x] correct
- [x] correctSync
- [x] stem
- [x] stemSync
- [x] generate
- [x] generateSync
- [x] analyze
- [x] analyzeSync
- [x] addDictionary
- [x] addDictionarySync

After...

- [x] Implementation passes all tests
- [x] Code cleanup
- [x] Document (See #38)

*Investigate parameters (see #44)

---

**Original Message**
@wooorm, Regarding matching the Hunspell(3) interface, do you mean [this one](http://linux.die.net/man/3/hunspell)? Are you suggesting instead of something like `spellSuggestions`, we have `suggest` in the exposed javascript API?

**Comment by wooorm** [comment]
Yes! But then camelcased, and also some things, like 'add' and 'addWithAffix' could be in one signature IMO

**Comment by Wulf** [comment]
Should we deprecate the old API and remove it in the future then? I don't want to break projects lol

**Comment by wooorm** [comment]
I’d say just refactor completely, drop old behaviour (note that it wasn’t working properly so it doesn’t break many libraries), and release a major version!

**Comment by Wulf** [comment]
**New API proposal**

Reason: to have a direct 1:1 mapping between nodehun and hunspell's API.

Format: `currentSignature`:`hunspellSignature`

Changed
- `addWord`: `add`*
- `addWordSync`: `addSync`
- `removeWord`: `remove`
- `removeWordSync`: `removeSync`
- `spellSuggest`: `suggest`
- `spellSuggestSync`: `suggestSync`

Unchanged
- `stem`: `stem`
- `stemSync`: `stemSync`
- `generate`: `generate`
- `generateSync`: `generateSync`
- `analyze`: `analyze`
- `analyzeSync`: `analyzeSync`

Reluctant to Change
- `isCorrect`: `spell`
- `isCorrectSync`: `spellSync`
- `addDictionary`: `addDic`
- `addDictionarySync`: `addDicSync`

* investigate parameters

**Comment by wooorm** [comment]
Hunspell(3) has a `spell` method which is different from `isCorrect`, so I’d suggest `isCorrect` > `correct` and keep `spell` unused so we can maybe add it later:

```c
int spell(const char *word, int *info, char **root);
```

**Comment by wooorm** [comment]
(otherwise I'm 👍)

**Comment by Wulf** [comment]
Updated the proposal.

**Comment by Wulf** [comment]
@wooorm hope things are well.

Thanks a lot for pushing for 1:1 naming between hunspell and nodehun. The API changes we agreed upon here are applied in v3.0.0 with one caveat:

* instead of `correct`/`correctSync`, I opted to use `spell`/`spellSync`.

There are two main for this:

1. Checking the spelling of a word is done via the `int spell(...)` method that hunspell exposes, thus, using `spell` would be 1:1
2. Since almost every method exposed by `nodehun` and `hunspell` is a verb, it might be confusing to use `correct('colour')`. Some users may assume `correct` will return a correct spelling, not just the boolean value which the method returns.

Of course, those that are already using nodehun v2 may be confused by this change, so I'll add an note to the v2 -> v3 doc.

Thanks for your patience with these changes :)
