### ISSUE TITLE
Dictionary Management

### ISSUE THREAD

**Issue by Wulf** [Wulf/nodehun#39]
@wooorm Let's dicuss dictionary management here.

**Comment by wooorm** [comment]
Could we support passing in an [object](https://github.com/wooorm/dictionaries) with `{aff: Buffer, dic: Buffer}`? ...when constructing like so: `new NodeHun()`?

And possible with `createNewNodehun(func, cb)`, where `func` is a function like the dictionary-loaders from [`wooorm/dictionaries`](https://github.com/wooorm/dictionaries/tree/master/dictionaries/nn_NO#usage) (this integration would make it quite easy to use).

Also: multiple `.aff` files doesn’t work, but multiple `.dic` files does, so someone could create a `.dic` file which provides medical term on top of `en_US.aff`, and `en_US.dic`. It would be really cool if the objects could be like this as well: `{aff: Buffer, dic: Array.<Buffer>}`

**Comment by Wulf** [comment]
Another note: [hunspell(3)](https://linux.die.net/man/3/hunspell) suggests that a max of 20 dictionaries can be added.

**Comment by Wulf** [comment]
Closing; if there are others who would like to see this feature, please feel free to reopen this issue!
