### ISSUE TITLE
Arguments of `callback` for `#spellSuggestions()`

### ISSUE THREAD

**Issue by wooorm** [Wulf/nodehun#42]
`callback` in `#spellSuggestions(value, callback)`, is given multiple arguments (`err`, `correct`, `suggestions`, `origWord`).  It would be more in line with Node-style APIs if an object would be given instead, with these parameters.

**Comment by Wulf** [comment]
Hey @wooorm, thanks for this suggestion. I agreed with you when I first saw this request, and I think the new API resolves this concern since it supports Promises (and thus `async/await`) out-of-the-box:

```
import { Nodehun } from 'nodehun'

const nodehun = new Nodehun(/* en_US */)

async function test() {
    const suggestions = await nodehun.suggest('colour')
    // => ['color', ... ]
    const suggestions2 = await nodehun.suggest('color')
    // => null (it is correct)
}

test()
```

Going to close this issue, but feel free to reopen it or continue the discussion.
