### ISSUE TITLE
Duplication: why do both `spellSuggestions` and `spellSuggestion` exist?

### ISSUE THREAD

**Issue by wooorm** [Wulf/nodehun#43]
We should fix this in the API refactor. Right now, the difference in their names makes me expect `suggest` would pass only the best suggestion.

**Comment by Wulf** [comment]
Good call. Relates to #37.

**Comment by Wulf** [comment]
`spellSuggest` and `spellSuggestSync` have been dropped in the `nan` branch (which implements API described in #37).

Reason: The native code which fetches a single suggestion isn't more efficient than that which fetches multiple suggestions.
