### ISSUE TITLE
Low response rate

### ISSUE THREAD

**Issue by Arnoku** [Wulf/nodehun#48]
Amazing job on the spellcheck, however, through extensive testing, I noticed that on average it handles around 20 requests per 5-8 seconds, which is not a high number if using in production environment.  
Could you please suggest ways to improve the speed? I've tried _filecache_ as well and it didn't help me much, thank you and sorry if this is not the appropriate place to ask this, but I need to know :)

**Comment by wooorm** [comment]
From my experience, and knowledge implementing suggestions, is that they’re always *very* slow. 

Thus, the simplest would be to cap the amount of words you find suggestions for: for example, at 10.
Showing if a word is misspelt or not is a much cheaper operation, so you can still show wrongly spelt words at pretty okay speed.

Another thing is to add a cache: often the same words are misspelt over and over, and there’s no need to look up suggestions for the same word multiple times.

**Comment by Arnoku** [comment]
@wooorm I thank you for your rapid response  
I do indeed use optimizations for the latter thing you mentioned - filter out the same words. For the specific thing I'm trying to make, I don't need suggestions, only to have the word be checked against a .dic/.aff dictionary, and figure out if the word is in the dictionary or not, I've tried using both **suggest** and **isCorrect** methods, since I assume the isCorrect method should work much faster, since it doesn't return suggestions, which might explain why it takes more time, since the method itself on the inside does more operations I assume  
Why I'm asking all this is I've tried using PHP's spellchecker before and I've gotten up to 2000 requests per 5 seconds by simply caching the dictionary file into memory, so this is why I'm curious if I'm doing anything wrong here?  
Thank you again for taking time to read and respond to my questions, cheers

**Comment by wooorm** [comment]
What’s your code? What dictionary do you use in PHP, and what in Node?

**Comment by Arnoku** [comment]
I've managed to figure it out, thanks a million, I've been doing it wrongly, instead of caching the physical files themselves, if you cache the **nodehun** objects, that's how you get MUCH faster response times. My bad I suppose, thank you so much nonetheless!
