### ISSUE TITLE
 import _multiprocessing > ImportError: DLL load failed: %1 

### ISSUE THREAD

**Issue by carllx** [Wulf/nodehun#49]
This is a very meaningful project, but I got error when npm install.

> $ npm install nodehun -save
> 
> > nodehun@2.0.11 install C:\Users\yam\Desktop\leonardo_parla\node_modules\nodehun
> > node-gyp rebuild
> 
> C:\Users\yam\Desktop\leonardo_parla\node_modules\nodehun>if not defined npm_config_node_gyp (node "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Traceback (most recent call last):
>   File "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
>     import gyp
>   File "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 8, in <module>
>     import gyp.input
>   File "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 15, in <module>
>     import multiprocessing
>   File "D:\Python27\lib\multiprocessing__init__.py", line 84, in <module>
>     import _multiprocessing
> ImportError: DLL load failed: %1 ▒▒▒▒▒▒Ч▒▒ Win32 Ӧ▒ó▒▒▒
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\yam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "D:\Program Files\nodejs\node.exe" "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\yam\Desktop\leonardo_parla\node_modules\nodehun
> gyp ERR! node -v v6.8.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "D:\Program Files\nodejs\node.exe" "C:\Users\yam\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "nodehun" "-save"
> npm ERR! node v6.8.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> 
> npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nodehun@2.0.11 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the nodehun package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nodehun
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls nodehun
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\yam\Desktop\leonardo_parla\npm-debug.log

**Comment by Wulf** [comment]
Hi Carlix, it seems you're on windows! I've had a lot of trouble getting it to work with windows too. I managed to get it working after reading the requirements for [`node-gyp`](https://github.com/nodejs/node-gyp/blob/master/README.md).

**Comment by Wulf** [comment]
@carllx any update on this?
