### ISSUE TITLE
Can this be used to differentiate nouns, adjectives, adverbs, etc.?

### ISSUE THREAD

**Issue by callodacity** [Wulf/nodehun#57]
I'm looking for a way to check if a word is a noun, adjective, verb, adverb or conjunction. 

I've tried looking through the hunspell documentation for `analyze` but I don't think I can use the information from that to differentiate between word types.

Do you know if this is at all possible with `nodehun`?

**Comment by Wulf** [comment]
Hi @callodacity,

Actually, Hunspell does support this! Check out the [Morphological analysis](http://www.manpagez.com/man/4/hunspell/) section in the hunspell docs.

Here's the example from the hunspell docs, but it uses `nodehun`:

```javascript
var affbuf = Buffer.from(`SET UTF-8\nTRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ\nSFX X Y 1\nSFX X 0 able . ds:able`)
var dictbuf = Buffer.from(`1\ndrink/X po:verb`)

var dict = new nodehun(affbuf,dictbuf);

console.log(dict.analyzeSync('drink'))      // [ ' st:drink po:verb' ]
console.log(dict.analyzeSync('drinkable'))  // [ ' st:drink po:verb ds:able' ]

```

**Comment by callodacity** [comment]
@Wulf thanks for the response!

Do I need a special dictionary to get that data? This is what I'm getting now:

```js
const nodehun = require('nodehun');
const loadDict = require('dictionary-en-au');

loadDict(function (err, data) {
  if (err) throw err;
  const dict = new nodehun(data.aff, data.dic);

  console.log(dict.analyzeSync('drink'))      // [ ' st:drink' ]
  console.log(dict.analyzeSync('drinkable'))  // [ ' st:drinkable', ' st:drink fl:B' ]
});
```
As you can see I'm not getting the `"po:verb"` part from `analyze`.

**Comment by Wulf** [comment]
Uh-huh, you need a dictionary which contains all the metadata defining whatever you need.

`fl:B` just indicates that the word is flagged with B. Glance over the "Twofold suffix stripping" example in the [hunspell docs](http://www.manpagez.com/man/4/hunspell/) - notice how the `drink` entry in the dictionary file has the flag `X`? (`drink/X`).

**Comment by callodacity** [comment]
Perfect. Thank you so much for your help 👍
