### ISSUE TITLE
Inconsistent spellcheck results

### ISSUE THREAD

**Issue by sebastiandittrich** [Wulf/nodehun#59]
Sometimes, but only under certain conditions, Nodehun classifies words that are actually correct as false. I have attached a file that returns 66 instead of 26 spelling mistakes in some (very rare) cases.

[example.zip](https://github.com/Wulf/nodehun/files/1382889/example.zip)

**Comment by Wulf** [comment]
Thanks for reporting this, I'll check it out this weekend.

**Comment by Wulf** [comment]
hey @sebastiandittrich I went through your example and I wasn't able to reproduce 66 spelling mistakes at all. What conditions did you run this under?
