### ISSUE TITLE
Prepare for hunspell 1.7

### ISSUE THREAD

**Issue by loretoparisi** [Wulf/nodehun#64]
Hunspell 1.7 is almost [ready](https://github.com/hunspell/hunspell/commit/4ddd8ed5ca6484b930b111aec50c2750a6119a0f). This main version comes with a lot of changes and improvements. Do you have a timeline when it will be available in nodehun?
Thank you!

**Comment by Wulf** [comment]
Looks like it released even before your post hehe
https://github.com/hunspell/hunspell/releases/tag/v1.7.0

Feel free to suggest a plan of action!

**Comment by Wulf** [comment]
Closing, feel free to reopen!

**Comment by Wulf** [comment]
hey @vipranarayan14, let me know how I can help you with this!

**Comment by Wulf** [comment]
Yeah, it's a submodule, try recloning the repository using this:

```
git clone --recurse-submodules git@github.com:Wulf/nodehun.git
```

**Comment by Wulf** [comment]
Hey, I’m closing this for now. Feel free to reopen it

**Comment by vipranarayan14** [comment]
Sure. Got busy with other works. I will let you know when I start working on it.

**Comment by Wulf** [comment]
sounds good :)
