### ISSUE TITLE
Seems like Generate isn't working?

### ISSUE THREAD

**Issue by thiagorova** [Wulf/nodehun#65]
So... I just tried generate with dictionaries downloaded with `hunspell-dict-downloader`. I'm not sure if I'm the idiot here, or if generate is just not working... As in not working, I mean the response is always an empty array
Here's what I did (it was doing a very initial test, so forgive the sync stuff):
```
var nodehun = require('nodehun')
var fs = require('fs')
var affbuf = fs.readFileSync("dictionary_path.aff")
var dictbuf = fs.readFileSync("dictionary_path.dic")
dict = new nodehun(affbuf,dictbuf)
dict.generate('tell', 'ran', (err, res)=>console.log(res))
dict.generate('telling', 'ran', (err, res)=>console.log(res))
```
on the same note, I tried using analyse on some words, and it gave a rather funky response as well... Since I'm not sure if they are related or not, i'll post one here:
PS: err was null in all of them here. I'm omitting it from the results to make it more readable
`dict.analyze('telling',(err, fields) => console.log(fields)) // [" st:telling", " st:tell fl:G"]`

as you can see, I think the result is not wrong per se. It seems to be giving me the original dictionary word and the affix rule that defines the flection, but it's a little different from was in the docs, here:
```
dict.analyze('telling',function(err, fields) => console.log(fields)) 
// [ ' st:telling ts:0', ' st:tell ts:0 al:told is:Vg' ]
```
(not that I really have any idea what this means, anyway.)

I took some time to check, and the files you suggest from the libre office are the same being served by `hunspell-dict-downloader`. Is this a peculiarity to the en_US, perhaps?
anyways, thanks a lot again!

**Comment by thiagorova** [comment]
btw, just to let you know, I tested with pt-br and en-au language files. This is where my last question/suggestion came from... sorry about that

**Comment by Wulf** [comment]
Thanks for reporting this, I'll look into it on the weeekend :)

**Comment by Wulf** [comment]
Hey @thiagorova, hope all is well.

You were on the mark with the problem being the language files you were using. 

`.aff` files that are commonly available often don't have enough data to produce useful output for `generate()` and `analyze()`. 

The `examples/dictionaries` folder has dictionary files downloaded from LibreOffice's repository and they have enough metadata to produce useful output.

Perhaps you'll find more descriptive language files from one of these sources: 

* [Libre Office dictionaries](http://cgit.freedesktop.org/libreoffice/dictionaries/tree/)
* [Official Aspell dictionaries](http://wordlist.aspell.net/dicts/)
* [Open Office extensions](http://extensions.services.openoffice.org/dictionary)
* [Mozilla Extensions](https://addons.mozilla.org/en-us/firefox/language-tools/)

Closing this for now, feel free to comment/reopen the issue :)

**Comment by thiagorova** [comment]
i see... thanks a lot for confirming it, though!
I'll check these out for sure
