### ISSUE TITLE
Can't install nodehun with node 12.2.0

### ISSUE THREAD

**Issue by zomilanovic** [Wulf/nodehun#66]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/milo/GitHub/GaneschaLabs/Ganescha-Spellcheck/node_modules/nodehun
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN grunt-file-sloc@0.0.1 requires a peer of grunt@~0.4.5 but none is installed. You must install peer dependencies yourself.
npm WARN ganescha-spellcheck@0.0.11 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodehun@2.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodehun@2.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/milo/.npm/_logs/2019-05-17T08_36_42_754Z-debug.log
```

**Comment by Wulf** [comment]
Thanks for reporting this, looks like those deprecation warnings have caught up.

That `nan` rewrite is now necessary. Actually, it would be interesting to ditch that effort and use `napi` as it's maintained alongside node.js.

Will try to get to this soon!

**Comment by loretoparisi** [comment]
@Wulf thanks, so it should be the same of https://github.com/Wulf/nodehun/issues/74?

**Comment by Wulf** [comment]
@loretoparisi seems like it.

@zomilanovic thanks for your patience, could I request you try nodehun 3 and see if it solves your compilation issue?

```
npm i -S wulf/nodehun#n-api
```

**Comment by vishnusankaran** [comment]
Hi @Wulf , I am unable to see the latest release in https://www.npmjs.com/package/nodehun

Since node-gyp depends on
https://www.npmjs.com/package/proofreader
https://www.npmjs.com/package/spellchecker_ptbr
https://www.npmjs.com/package/proofread-core
https://www.npmjs.com/package/writewell

and they have `nodehun` as a dependency, they also would need to update this?

**Comment by Wulf** [comment]
@vishnusankaran, thanks for checking in. No release yet. I'm hoping to hear back from some others before publishing it to npm.

As for packages that depend on `nodehun`, they would definitely need to update to 3.0 once it's released if they intend to target node version 12 or higher.

If you want to try 3.0 even though it's not released, please try specifying the branch when installing:

```
npm i -S wulf/nodehun#n-api
```

**Comment by zomilanovic** [comment]
I tried installing nodehun 3 and it seems the compilation issue is gone.

**Comment by loretoparisi** [comment]
@zomilanovic on which OS you were successful?

**Comment by zomilanovic** [comment]
@loretoparisi macOS Catalina 10.15.1

**Comment by loretoparisi** [comment]
@zomilanovic ok thank you. By the way at the end I was able to make it working too, so for me green light!!! Thanks.

**Comment by Wulf** [comment]
Thanks for verifying!
