### ISSUE TITLE
Can't install nodehun with node 11.11.0

### ISSUE THREAD

**Issue by mohamedsahadkp** [Wulf/nodehun#70]

**Comment by Wulf** [comment]
Yikes, thanks for reporting this.

**Comment by Wulf** [comment]
We need to change the node versions that the tests are run on

**Comment by mohamedsahadkp** [comment]
Which version?

**Comment by Wulf** [comment]
Sorry @mohamedsahadkp, seems I forgot to reply back -- thanks for your patience. 

Could I request you to try nodehun 3 and see if it resolves your issue?

```
npm i -S wulf/nodehun#n-api
```

**Comment by Wulf** [comment]
I'm going to close this issue but feel free to reopen it or continue the discussion :)
