### ISSUE TITLE
Add TypeScript bindings

### ISSUE THREAD

**Issue by bbenoist** [Wulf/nodehun#71]
It would be cool to have [TypeScript type definitions](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for the library. 

After a few searches, it looks like using [nbind](https://github.com/charto/nbind) could do the trick if you don't want to write them by yourself (as in [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs/tree/master/lib/typings) for example).

**Comment by Wulf** [comment]
This will be featured in 3.0.0, thanks @bbenoist.

If you're keen to try it now:

```
npm i -S wulf/nodehun#n-api
```
