### ISSUE TITLE
Can't install nodehun with node 10.16.2

### ISSUE THREAD

**Issue by trofim24** [Wulf/nodehun#72]
`error C2144: syntax error : 'int' should be preceded by ';' (..\src\nodehun.cpp)`
`error C4430: missing type specifier - int assumed. Note: C++ does not support default-int`

**Comment by Wulf** [comment]
Hey @trofim24, thanks for your patience. Please let me know if the n-api build solves your issue:

```
npm i -S wulf/nodehun#n-api
```

**Comment by Wulf** [comment]
3.0.0 seems to have resolved the compilation issues, feel free to reopen this or continue the discussion :)
