### ISSUE TITLE
Git clone with submodules failed

### ISSUE THREAD

**Issue by ShockwaveNN** [Wulf/nodehun#73]
Run
`git clone --recurse-submodules https://github.com/Wulf/nodehun.git`

Result:
```
error: Server does not allow request for unadvertised object a7601cf3608c5690aa14851bb132b13fa0a8aa2b
Fetched in submodule path 'src/hunspell', but it did not contain a7601cf3608c5690aa14851bb132b13fa0a8aa2b. Direct fetching of that commit failed.
```

Seems related that https://github.com/Wulf/nodehun/tree/master/src -> `hunspell @ a7601cf` link to 404

**Comment by trofim24** [comment]
Nathanjsweet archived his repository forked from 'hunspell'. May we resume the transition to the original 'hunspell' - https://github.com/Wulf/nodehun/pull/51 ?

**Comment by Wulf** [comment]
hey @ShockwaveNN, I forked the original repo so this shouldn't be a problem anymore. Feel free to reopen this issue or continue the discussion. 

@trofim24 sorry but I don't think we can abandon support for buffers. It's like Nathan said -- users of the library still rely on them.

Going to close this. Please create a new issue or reopen #51 if you feel that's an important step forward.
