### ISSUE TITLE
Publish Nodehun v3

### ISSUE THREAD

**Issue by Wulf** [Wulf/nodehun#75]
The `n-api` branch is almost ready to be merged into master.

It should resolve the following issues:

#74  node-v12.13.0 error 
#73  Git clone with submodules failed 
#72  Can't install nodehun with node 10.16.2 
#71  Add TypeScript bindings 
#70  Can't install nodehun with node 11.11.0 
#69  addWithAffix
#66  Can't install nodehun with node 12.2.0 
#55  spellSuggest, promises, and express 
#42  Arguments of `callback` for `#spellSuggestions()` 
#37  Match Hunspell(3) interface 

Some TODO items are listed in the readme file on the `n-api` branch which should be resolved before releasing v3.

Briefly, this merge will feature the following:

* Completely re-written using N-API (thus, stability in future v8 versions)
* Added TypeScript declarations
* Promise-based async API
* Exposes all hunspell functions
  * getDictionaryEncoding(): string | undefined;
  * getWordCharacters(): string | undefined;
  * getWordCharactersUTF16(): string | undefined;
  * getVersion(): string | undefined;
* Switched from tape to mocha
* Many more tests

:rocket: thanks for your patience everyone!

**Comment by loretoparisi** [comment]
@Wulf I don't see a refactoring of `isCorrectSync`: `TypeError: this.dictionary.isCorrectSync is not a function`. Which is the replacement?
