### ISSUE TITLE
Nodehun and Hunspell produce different results

### ISSUE THREAD

**Issue by dfoteinakis** [Wulf/nodehun#79]
I'm testing with Hungarian dictionaries found [here](https://github.com/titoBouzout/Dictionaries) as well as the ones coming from 
`
apt-get install hunspell-hu
`
I have tested with v.2.x of Nodehun as well as the latest  version (3.0.1). I have tested with node 8.6 and v12.16.1.

This is hunspell output form command line:

```
Hunspell 1.6.2 - Magyar 1.6     
végrehajtási
+ végrehajt

rendelete
+ rendelet
```

The sample code i'm using to test with nodehun:
```
let lang = 'hu_HU';
let affbuf = fs.readFileSync(__dirname +  '/dictionaries/'+lang+'/'+lang+'.aff');
let dictbuf = fs.readFileSync(__dirname +  '/dictionaries/'+lang+'/'+lang+'.dic');
let huHU_Nodehun =  new Nodehun(affbuf,dictbuf);

huHU_Nodehun.spell('végrehajtási').then(function (isCorrect) {
    console.log(isCorrect); //prints false
    huHU_Nodehun.spell('rendelete').then(function (isCorrect) {
        console.log(isCorrect); //prints false
    });
});
```

Any ideas?

**Comment by niftylettuce** [comment]
Bump

**Comment by niftylettuce** [comment]
Nevermind, I am seeing the same results.
