### ISSUE TITLE
Hunspell GPL license

### ISSUE THREAD

**Issue by victorborrasdev** [Wulf/nodehun#92]
Hi! I'm considering using Nodehun for a commercial SaaS, but I'm a little confused by the license. My knowledge in this realm is minimal, but if I understand correctly, this uses Hunspell, which is GPL. Wouldn't this license apply to Nodehun as well? Then, if that's the case, I can't use it in my project, am I right?

Thanks in advance!

**Comment by Wulf** [comment]
Hey Victor, hope things are well!

Any of the wrapper code is licensed under [LICENSE.md](https://github.com/Wulf/nodehun/blob/master/LICENSE.md), but as you suggested, this does compile a fork of hunspell and so its license will also need to be taken into consideration.

Not sure about the other details, sorry.

**Comment by victorborrasdev** [comment]
Ok, thank you very much 😄
