### ISSUE TITLE
React app can´t find module

### ISSUE THREAD

**Issue by imigueldiaz** [Wulf/nodehun#95]
Hi,

Using on my App.tsx

`import { Nodehun } from "nodehun";`

when I launch my react application compilation from powershell with

`yarn react-start`

 It crrashes with message:

```
./src/App.tsx
Module not found: Can't resolve 'nodehun' in 'D:\Proyectos\node\electron\drafts-reviewer-electron-react\src'
```

Is it possible to load  nodehun on a React application or I need to create a separate application as API to interact with React?

Best!

**Comment by Wulf** [comment]
It should work in electron :)

**Comment by imigueldiaz** [comment]
I'll try on electron files, thanks! 👍🏼
