### ISSUE TITLE
What version of Hunspell is used here?

### ISSUE THREAD

**Issue by vipranarayan14** [Wulf/nodehun#97]
Hi
I am using nodehun for automatically testing the dictionary that I am developing for Hunspell. So, I want to know to which version of the [main hunspell](https://github.com/hunspell/hunspell/), the fork used here correspond.

I checked the readme, the 'hunspell' folder, issues, etc. But I couldn't find the version of the Hunspell used here. From issue #64, I could infer that it is not the latest.

Can you shed some light here, please?

BTW, Nodehun is great. It has made my dictionary creation workflow easy and efficient. Thank you.

**Comment by Wulf** [comment]
Hey @vipranarayan14, thanks for reaching out.

The fork uses `1.3.2` but it could be a few commits on top of this version. I'm hoping Hunspell 2 will have a buffer interface, in which case, we'll switch and use the main branch.

Relevant issues here:
https://github.com/hunspell/hunspell/pull/443
https://github.com/hunspell/hunspell/issues/603

**Comment by Wulf** [comment]
It's just because of time. 

I think if we rebase the work done [here](https://github.com/hunspell/hunspell/pull/443/files) on top of 1.7.0, we can use that as a fork instead.

I'm going to close this issue for now, but please feel free to open another one pertaining to updating the fork :-)

**Comment by vipranarayan14** [comment]
Thanks, @Wulf.

Surely, updating to 1.7.0 will help me and might also help [many others who use nodehun](https://www.npmjs.com/browse/depended/nodehun). I want to work on this.

I checked the files in [the PR](https://github.com/hunspell/hunspell/pull/443/files) you shared and compared some of the files with the current version's files. As far as what I can see, it seems doable for me. But my c++ knowledge is very basic. So, if you can help me when I get stuck, I can make the required changes and submit a PR.

Instead of opening a new issue for this discussion, I think we can reopen and use issue #64.

**Comment by vipranarayan14** [comment]
okay, great! I will start working on it.
